version: '3'

description: >
  task slingshot-build
  task wasm-build
  task serve-file
  task wasm-download-run
  
tasks:
  # task slingshot-build
  slingshot-build:
    cmds:
      - | 
        target=$(pwd)
        cd ../../../slingshot-server
        env CGO_ENABLED=0 go build -ldflags="-s -w" -o ${target}/slingshot

  # task wasm-build
  wasm-build:
    cmds:
      - | 
        cd ../10-pdk-api
        tinygo build -scheduler=none --no-debug \
          -o print.wasm \
          -target wasi main.go

        ls -lh *.wasm

  # task serve-file
  serve-file:
    cmds:
      - | 
        cd ../10-pdk-api
        python3 -m http.server 9000

  # task wasm-download-run
  wasm-download-run:
    description: >
      http://0.0.0.0:9000/print.wasm
    cmds:
      - | 
        ./slingshot run \
          --wasm-url="http://0.0.0.0:9000/print.wasm" \
          --wasm=./print.wasm \
          --handler=callHandler \
          --input="🤓 I'm a geek" \
          --log-level info \
          --allow-hosts *,*.google.com,yo.com \
          --config '{"firstName":"Borane","lastName":"Morane"}' \
          --allow-paths '{"testdata":"./"}'

  # task all
  all:
    cmds:
      - task slingshot-build
      - task wasm-build
      - task wasm-run
