site_name: SlingShot
site_url: https://bots-garden.github.io/slingshot/
site_author: Philippe Charrière (@k33g)
site_description: >-
  **SlingShot** is a **WebAssembly Extism Plugins Runner**.
# Repository
repo_name: bots-garden/slingshot
repo_url: https://github.com/bots-garden/slingshot

# Copyright
copyright: Copyright &copy; 2023 - 2024 Philippe Charrière


nav:
    - 🏠 Home: index.md
    - 🚀 Write Extism plug-ins:
      - CLI plug-in: write-plug-in.md
      - HTTP nano-service plug-in: write-service.md
      - Redis subscriber plug-in: write-redis-subscriber.md
      - Redis publisher plug-in: write-redis-publisher.md
      - Nats subscriber plug-in: write-nats-subscriber.md
      - Nats publisher plug-in: write-nats-publisher.md
    - 🛠️ Host functions: 
      - Intro: host-functions/intro.md
      - Display: host-functions/display.md
      - Environment: host-functions/env.md
      - Memory cache: host-functions/mem.md
      - Redis cache: host-functions/redis.md
      - Redis PubSub: host-functions/redis-pubsub.md
      - Nats: host-functions/nats.md
      - Files: host-functions/files.md
    - 🟣 Write Slingshot plug-ins:
      - Slingdhot PDK: slingshot-pdk/intro.md
      - Go PDK: slingshot-pdk/go-pdk.md
      - Rust PDK: slingshot-pdk/rust-pdk.md
    - 🚩 Extism flags: extism-flags.md



theme:
  name: material
  palette:
    primary: deep purple
  features:
    #- announce.dismiss
    #- content.action.edit
    #- content.action.view
    #- content.code.annotate
    #- content.code.copy
    # - content.code.select
    # - content.tabs.link
    #- content.tooltips
    # - header.autohide
    # - navigation.expand
    #- navigation.footer
    #- navigation.indexes
    # - navigation.instant
    # - navigation.prune
    #- navigation.sections
    #- navigation.tabs
    # - navigation.tabs.sticky
    #- navigation.top
    #- navigation.tracking
    #- search.highlight
    #- search.share
    #- search.suggest
    #- toc.follow
    # - toc.integrate
extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      use_pygments: true
      auto_title: false
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      line_spans: __span
#theme:
#    name: readthedocs
#    highlightjs: true
#    hljs_languages:
#        - yaml
#        - rust
#        - golang
#        - bash
#        - javascript
