version: '3'

description: >
  # ...

tasks:
  # task mkdocs:install
  install:
    cmds:
      - pipx install mkdocs-material --include-deps
  # task mkdocs:serve
  serve:
    cmds:
      - mkdocs serve
  # task mkdocs:publish
  publish: # on the `main` branch
    cmds:
      - mkdocs gh-deploy
