version: '3'

description: >
  task slingshot-build
  task wasm-build
  task wasm-run
  
tasks:
  # task slingshot-build
  slingshot-build:
    cmds:
      - | 
        target=$(pwd)
        cd ../../../slingshot-server
        env CGO_ENABLED=0 go build -ldflags="-s -w" -o ${target}/slingshot

  # task wasm-build
  wasm-build:
    cmds:
      - | 
        tinygo build -scheduler=none --no-debug \
          -o redispub.wasm \
          -target wasi main.go

        ls -lh *.wasm

  # task wasm-run
  wasm-run:
    cmds:
      - | 
        set -o allexport; source .env; set +o allexport
        # you need these environment variables
        # - REDIS_URI
        # echo "REDIS_URI: ${REDIS_URI}"
        ./slingshot run --wasm=./redispub.wasm \
        --handler=publish \
        --input="I 💜 Wasm ✨"

  # task all
  all:
    cmds:
      - task slingshot-build
      - task wasm-build
      - task wasm-run
