version: '3'

description: >
  task slingshot-build
  task wasm-build
  task wasm-run

tasks:
  # task slingshot-build
  slingshot-build:
    cmds:
      - | 
        target=$(pwd)
        cd ../../../slingshot-server
        env CGO_ENABLED=0 go build -ldflags="-s -w" -o ${target}/slingshot

  # task wasm-build
  wasm-build:
    cmds:
      - | 
        cargo clean
        cargo build --release --target wasm32-wasi #--offline
        # ls -lh *.wasm
        ls -lh ./target/wasm32-wasi/release/*.wasm
        cp ./target/wasm32-wasi/release/*.wasm .

  # task wasm-run
  wasm-run:
    cmds:
      - | 
        ./slingshot cli --wasm=./hello.wasm --handler=hello --input="Bob 🤓"

  # task all
  all:
    cmds:
      - task slingshot-build
      - task wasm-build
      - task wasm-run
