version: '3'

description: >
  task slingshot-build
  task wasm-build
  task serve-file
  task wasm-download-run
  
tasks:
  # task slingshot-build
  slingshot-build:
    cmds:
      - | 
        target=$(pwd)
        cd ../../../slingshot-server
        env CGO_ENABLED=0 go build -ldflags="-s -w" -o ${target}/slingshot

  # task wasm-build
  wasm-build:
    cmds:
      - | 
        cd ../06-redis-sub
        tinygo build -scheduler=none --no-debug \
          -o redissub.wasm \
          -target wasi main.go

        ls -lh *.wasm

  # task serve-file
  serve-file:
    cmds:
      - | 
        cd ../06-redis-sub
        python3 -m http.server 9000


  # task wasm-download-run
  wasm-download-run:
    description: >
      To test:
      set -o allexport; source .env; set +o allexport
      redis-cli -u  ${REDIS_URI}
      redis.aivencloud.com:17170> PUBLISH news "Hello World"
    cmds:
      - | 
        set -o allexport; source .env; set +o allexport
        # you need these environment variables
        # - REDIS_URI
        # echo "REDIS_URI: ${REDIS_URI}"

        ./slingshot redis subscribe \
        --wasm-url="http://0.0.0.0:9000/redissub.wasm" \
        --wasm=./redissub.wasm \
        --handler=callHandler \
        --uri=${REDIS_URI} \
        --client-id=pubsubcli \
        --channel=news

  # task all
  all:
    cmds:
      - task slingshot-build
      - task wasm-build
      - task wasm-run

  